name: Clojure CI Windows

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      # Uses sha for added security since tags can be updated
      uses: joschi/setup-jdk@b9cc6eabf7e7e3889766b5cee486f874c9e1bd2d
      with:
        java-version: 11
    - name: Set up Lein
      run: choco install lein
    - name: Install dependencies
      run: lein.bat deps
    - name: Run tests
      run: lein.bat test
